package com.harpy.harpyserver.repository;

import com.google.cloud.firestore.CollectionReference;
import com.google.cloud.firestore.DocumentSnapshot;
import com.google.cloud.firestore.Firestore;
import com.google.cloud.firestore.QueryDocumentSnapshot;
import com.google.gson.Gson;
import com.harpy.harpyserver.entity.AccountDetails;
import com.harpy.harpyserver.model.FirebaseCollection;
import com.harpy.harpyserver.model.Skill;
import com.harpy.harpyserver.util.NumberUtil;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Repository;

import javax.annotation.PostConstruct;
import java.util.*;
import java.util.stream.Collectors;

@Repository
@RequiredArgsConstructor
public class AccountRepository {

    private final Firestore firestore;
    String json = "[{\n" +
            "  \"pin\": 1202,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"mmenaul0@pagesperso-orange.fr\",\n" +
            "  \"password\": \"HeHq8QyobUS\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"871f690c-8c51-4592-860d-412db6f32339\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"243.214.155.128\",\n" +
            "  \"proxyPort\": 4871759,\n" +
            "  \"proxyUser\": \"ckloster0\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"g6UKqvzgfo\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 8949,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"pcodd1@dell.com\",\n" +
            "  \"password\": \"J59pzYb\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"090809cd-3440-4b95-a234-162b7e8b7632\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"10.145.207.14\",\n" +
            "  \"proxyPort\": 25081676,\n" +
            "  \"proxyUser\": \"lroseman1\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"QO7V0f0o\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 2180,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"ldowbekin2@wufoo.com\",\n" +
            "  \"password\": \"0eaTp6QkbImS\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"fe6abd3e-a541-4a51-af1f-f14fcf2fdc96\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"47.175.112.244\",\n" +
            "  \"proxyPort\": 12672361,\n" +
            "  \"proxyUser\": \"bmatokhnin2\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"e2aQmVgi\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 2948,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"kprudence3@theguardian.com\",\n" +
            "  \"password\": \"foySKfeSW\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"e8d62adf-acf3-4999-9716-5c3569ed6fc7\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"93.231.250.93\",\n" +
            "  \"proxyPort\": 13365259,\n" +
            "  \"proxyUser\": \"skrystof3\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"NVXP1IVII2\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 1576,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"crolland4@nps.gov\",\n" +
            "  \"password\": \"aPhzmI\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"7ee59821-361e-4a13-9364-7378a743af5d\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"44.212.239.39\",\n" +
            "  \"proxyPort\": 25869768,\n" +
            "  \"proxyUser\": \"cbowser4\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"W60wLOyg\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 1854,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"rrainford5@statcounter.com\",\n" +
            "  \"password\": \"rMrBohhp\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"76716177-8bc5-4814-b748-30c21dc55342\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"169.195.22.193\",\n" +
            "  \"proxyPort\": 18957335,\n" +
            "  \"proxyUser\": \"brawsen5\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"YMxaMoIj\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 2058,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"aaldie6@opera.com\",\n" +
            "  \"password\": \"OU90GC9PN\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"4b8ed91f-5d8f-40c7-b7b8-58dc5128e4dc\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"129.95.93.136\",\n" +
            "  \"proxyPort\": 5150972,\n" +
            "  \"proxyUser\": \"genglefield6\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"fDq71KUePX\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 6388,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"tragsdall7@php.net\",\n" +
            "  \"password\": \"uNtenZsY\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"7dd22221-7d40-4ba1-90c5-a641546f2b5e\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"254.134.108.123\",\n" +
            "  \"proxyPort\": 11797494,\n" +
            "  \"proxyUser\": \"abigrigg7\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"HfFzexC4lAOH\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 9197,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"flenden8@jigsy.com\",\n" +
            "  \"password\": \"VnDo5sfaDvvX\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"03dc770f-ffaf-4362-a518-367007860e46\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"83.97.91.165\",\n" +
            "  \"proxyPort\": 1426230,\n" +
            "  \"proxyUser\": \"nmurford8\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"MuCNPXBGlnYk\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 7279,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"dtrime9@e-recht24.de\",\n" +
            "  \"password\": \"Mg0uaxVql1w\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"4b498bc7-2409-47b5-b0b9-d05d376a4e05\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"109.139.75.26\",\n" +
            "  \"proxyPort\": 11771005,\n" +
            "  \"proxyUser\": \"alowes9\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"Sb3kfQNqM\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 1297,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"wseabona@aboutads.info\",\n" +
            "  \"password\": \"FVfzYPon\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"85fccce8-1e44-4999-bd62-c0b8d4045a28\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"86.48.208.156\",\n" +
            "  \"proxyPort\": 24242652,\n" +
            "  \"proxyUser\": \"aoffilera\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"MXCquLZOD\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 2330,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"gberickb@psu.edu\",\n" +
            "  \"password\": \"XEyQj3e\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"3261b029-e134-467a-ad88-16cc892fc927\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"238.56.192.77\",\n" +
            "  \"proxyPort\": 22552819,\n" +
            "  \"proxyUser\": \"epeacheyb\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"7XcxoL0S8wr\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 7253,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"wlosemannc@mlb.com\",\n" +
            "  \"password\": \"vkEwDukt\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"f44d22d6-b006-4f83-9316-c680550b4940\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"159.226.224.104\",\n" +
            "  \"proxyPort\": 26925607,\n" +
            "  \"proxyUser\": \"dchavesc\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"APyORiL\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 5279,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"gcapseyd@marriott.com\",\n" +
            "  \"password\": \"ehIn0f\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"2f221285-36a5-4bc8-b1a1-19764c623fc0\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"115.30.78.110\",\n" +
            "  \"proxyPort\": 17503306,\n" +
            "  \"proxyUser\": \"htilerd\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"6yI7HT1u\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 7249,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"bsteptowee@com.com\",\n" +
            "  \"password\": \"e7KhHilK\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"93d8aea8-1383-488e-91ba-6349af81df01\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"129.19.56.66\",\n" +
            "  \"proxyPort\": 18290369,\n" +
            "  \"proxyUser\": \"ftomasinie\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"9PXc6NOUS\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 4985,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"eholtawayf@ycombinator.com\",\n" +
            "  \"password\": \"NEG5UOPfjRDU\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"c8ae1aa5-0f3d-451e-bb78-4a57dd741dc6\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"100.246.59.21\",\n" +
            "  \"proxyPort\": 5592882,\n" +
            "  \"proxyUser\": \"mcaskief\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"QiU4qm7hrLCB\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 2719,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"abloomfieldg@zimbio.com\",\n" +
            "  \"password\": \"vd8YcZcVs\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"4e88c54b-eb7c-4116-a061-7780f6652dfe\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"86.146.78.10\",\n" +
            "  \"proxyPort\": 14655561,\n" +
            "  \"proxyUser\": \"iraingerg\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"jdFFa9\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 8506,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"ljosth@list-manage.com\",\n" +
            "  \"password\": \"nzp4DvxNah\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"bd189c86-8218-4d2e-86b8-ce53c82c7dfe\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"53.198.255.39\",\n" +
            "  \"proxyPort\": 1345866,\n" +
            "  \"proxyUser\": \"nmccombh\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"0EkfQSGC\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 8843,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"klamplughi@list-manage.com\",\n" +
            "  \"password\": \"4Q7EDf3j\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"837ed7a5-daf6-404b-bb7f-209f4c95fd41\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"237.176.211.76\",\n" +
            "  \"proxyPort\": 28757253,\n" +
            "  \"proxyUser\": \"rfassei\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"1IWFLfXea\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 8500,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"mingreyj@umn.edu\",\n" +
            "  \"password\": \"FaVz6Zm\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"4385c987-da84-4d3c-8bd7-047bec6d8f8c\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"141.10.91.100\",\n" +
            "  \"proxyPort\": 13203791,\n" +
            "  \"proxyUser\": \"jrablj\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"rPf9fP\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 9401,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"meagellk@unicef.org\",\n" +
            "  \"password\": \"GSZED3C\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"24759f7e-ca83-4296-a7c0-d15361d76a91\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"68.134.207.67\",\n" +
            "  \"proxyPort\": 5409721,\n" +
            "  \"proxyUser\": \"tdiperausk\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"Ls0Uqw\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 4690,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"dkemberl@google.com.hk\",\n" +
            "  \"password\": \"7eNDNuw1pgKf\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"0bde422d-96c7-4274-b453-840926c45751\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"164.249.68.33\",\n" +
            "  \"proxyPort\": 31034151,\n" +
            "  \"proxyUser\": \"bgoulleel\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"z3DK6Gj\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 9039,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"gdarridonm@amazon.co.uk\",\n" +
            "  \"password\": \"dxJFW3v\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"729b8fd6-129c-4351-9e0e-00a1523a060b\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"20.144.83.43\",\n" +
            "  \"proxyPort\": 14739845,\n" +
            "  \"proxyUser\": \"lbenkom\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"yN9TbJlSR\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 1611,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"tbuxsyn@w3.org\",\n" +
            "  \"password\": \"jM6ib5\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"024ec53e-542a-46b6-a119-a2bc4a7c7c3e\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"74.95.190.146\",\n" +
            "  \"proxyPort\": 4605371,\n" +
            "  \"proxyUser\": \"gsiehardn\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"nC5dFWkl8\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 8383,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"kgrigso@bbb.org\",\n" +
            "  \"password\": \"8i65Il\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"d6d40800-b365-45be-825f-e1d14d3bbc5d\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"216.20.217.24\",\n" +
            "  \"proxyPort\": 257672,\n" +
            "  \"proxyUser\": \"lquadeo\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"Mz0inJgNB\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 1650,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"kmacconnellp@tumblr.com\",\n" +
            "  \"password\": \"DNxijMjCpGdZ\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"a23dd5b9-26e8-48aa-992e-f1daf1b35b81\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"13.45.162.157\",\n" +
            "  \"proxyPort\": 9534315,\n" +
            "  \"proxyUser\": \"nsimanenkop\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"HP7jRRD\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 8533,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"saberhartq@parallels.com\",\n" +
            "  \"password\": \"qUK9QtW\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"da881ec5-5b3a-4bca-a0ec-d1183a0c01ae\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"223.141.216.205\",\n" +
            "  \"proxyPort\": 16340829,\n" +
            "  \"proxyUser\": \"rsyceq\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"h9SeHzTgvc\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 3288,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"lpashr@twitpic.com\",\n" +
            "  \"password\": \"YMfIUUbNIz\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"9fec2527-3283-4d43-9bbf-d5cf0d75264d\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"21.244.50.211\",\n" +
            "  \"proxyPort\": 18761101,\n" +
            "  \"proxyUser\": \"ncorbinr\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"SgSxMh\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 6132,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"ktuftss@aol.com\",\n" +
            "  \"password\": \"8i81uQ\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"167f0b70-0a4a-4328-b934-2983d209b8b3\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"2.128.79.170\",\n" +
            "  \"proxyPort\": 24247874,\n" +
            "  \"proxyUser\": \"hstairs\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"MNdhEm\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 2026,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"bdunphiet@constantcontact.com\",\n" +
            "  \"password\": \"6GaEDd3fz\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"10e30794-1e0c-45c9-af55-a24412ed37d5\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"181.29.245.47\",\n" +
            "  \"proxyPort\": 15839413,\n" +
            "  \"proxyUser\": \"sboalert\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"LR61QHDCp2bp\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 1308,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"stootellu@patch.com\",\n" +
            "  \"password\": \"rYKimPT\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"8d8f4302-fd4d-4384-9593-7913a7411a8b\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"226.201.210.220\",\n" +
            "  \"proxyPort\": 26250427,\n" +
            "  \"proxyUser\": \"hduesberryu\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"Pw5fpXo6klH\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 9639,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"wbinnerv@vk.com\",\n" +
            "  \"password\": \"Ob8VVNdKmRY\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"b1f6bf4b-c94b-45c9-96da-adda9ef3b30d\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"41.51.104.62\",\n" +
            "  \"proxyPort\": 5694933,\n" +
            "  \"proxyUser\": \"mbettev\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"Y09Cq4bbh\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 5094,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"fferedayw@nifty.com\",\n" +
            "  \"password\": \"6NujlUbtZjK7\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"9c7cc9bd-c6fb-41e3-aafb-acceaf80e525\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"205.88.68.135\",\n" +
            "  \"proxyPort\": 179794,\n" +
            "  \"proxyUser\": \"ogutansw\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"6ChsmrE5iEJ\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 4756,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"hdowniex@tamu.edu\",\n" +
            "  \"password\": \"rl5HEMq\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"b2463720-cc37-422c-bc4b-27e148e87205\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"139.139.118.53\",\n" +
            "  \"proxyPort\": 19781531,\n" +
            "  \"proxyUser\": \"nlepruvostx\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"S1qNcM\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 8128,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"ascotty@free.fr\",\n" +
            "  \"password\": \"J48CDRNu5Bj\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"448a4632-21b6-4773-8183-ebb8d8374b55\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"152.206.240.232\",\n" +
            "  \"proxyPort\": 5333223,\n" +
            "  \"proxyUser\": \"dmackrilly\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"iQ4S1Z9Im\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 1787,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"jellingsworthz@theguardian.com\",\n" +
            "  \"password\": \"zO5oba0Fn1R\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"30fd3758-2c7d-45d5-b768-5bf94491d095\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"166.108.18.199\",\n" +
            "  \"proxyPort\": 15028403,\n" +
            "  \"proxyUser\": \"plicciardelloz\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"BEzYs8\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 8450,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"eburnham10@stumbleupon.com\",\n" +
            "  \"password\": \"lu3H6bHehzz\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"86ee6fff-cbf0-42d9-9414-ee36dcf42d66\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"68.32.75.213\",\n" +
            "  \"proxyPort\": 12693637,\n" +
            "  \"proxyUser\": \"mshrimptone10\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"wZ3eb7fAJ\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 1839,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"jfilochov11@mayoclinic.com\",\n" +
            "  \"password\": \"jU9WkZz\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"7af576e0-f160-41fd-8208-6e47002b00fd\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"84.131.37.75\",\n" +
            "  \"proxyPort\": 13814810,\n" +
            "  \"proxyUser\": \"dyaneev11\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"AtvCgfv0x\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 1429,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"evillalta12@aol.com\",\n" +
            "  \"password\": \"3j4KG3\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"fce321b3-08fa-46eb-9e97-3cab9b3743cc\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"73.54.202.30\",\n" +
            "  \"proxyPort\": 114457,\n" +
            "  \"proxyUser\": \"sgawen12\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"KTkUBdsuuI\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 9467,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"tbutts13@creativecommons.org\",\n" +
            "  \"password\": \"Ymz3fq\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"a8c5ed0e-f732-4b6e-8ff7-ef8aac3d534b\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"39.205.243.143\",\n" +
            "  \"proxyPort\": 17687280,\n" +
            "  \"proxyUser\": \"rberr13\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"tLKJVU\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 9446,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"sgilliard14@samsung.com\",\n" +
            "  \"password\": \"X9grQxjH3DP\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"ee9c4300-831a-46d5-96d6-963da3db3082\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"190.111.140.232\",\n" +
            "  \"proxyPort\": 3470312,\n" +
            "  \"proxyUser\": \"aparcall14\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"MtjOmKlXAgb5\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 4973,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"gcavnor15@123-reg.co.uk\",\n" +
            "  \"password\": \"0xorYUPlQBj\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"31cf63ee-697e-4205-be97-e6be439f9d62\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"145.245.184.120\",\n" +
            "  \"proxyPort\": 26373171,\n" +
            "  \"proxyUser\": \"ahuxter15\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"DVms6w\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 7235,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"fgainfort16@vimeo.com\",\n" +
            "  \"password\": \"Pn3QIdQe\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"b8932d35-156d-43d0-b4c7-0bd5410e3988\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"124.249.144.146\",\n" +
            "  \"proxyPort\": 22724918,\n" +
            "  \"proxyUser\": \"wamiranda16\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"ILvFglt\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 6755,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"gwedlock17@cbslocal.com\",\n" +
            "  \"password\": \"NljBVp\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"3d9ddc21-9ce9-496e-b7a3-e892aafd93f4\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"27.80.17.108\",\n" +
            "  \"proxyPort\": 16768508,\n" +
            "  \"proxyUser\": \"mdevonport17\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"y3naTq\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 4513,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"zwoodroff18@naver.com\",\n" +
            "  \"password\": \"4lnfivR3tJ\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"ba9b5fc9-7355-4e35-bdf9-56a5f6317949\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"43.98.5.200\",\n" +
            "  \"proxyPort\": 9471772,\n" +
            "  \"proxyUser\": \"nrimer18\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"vfhOLBFwgs\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 4025,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"mdelamar19@live.com\",\n" +
            "  \"password\": \"LofiK1CNa\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"79785776-d401-49a8-8220-e7e9c72a4f26\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"3.74.108.36\",\n" +
            "  \"proxyPort\": 24926846,\n" +
            "  \"proxyUser\": \"jlodwig19\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"3gJ4jgHs\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 7388,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"epoulston1a@kickstarter.com\",\n" +
            "  \"password\": \"QssBsE\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"a8c14acc-b1fc-4fb6-b7c6-69cd15d0e074\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"143.86.160.227\",\n" +
            "  \"proxyPort\": 3441137,\n" +
            "  \"proxyUser\": \"flemar1a\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"nScw1GY\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 9197,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"rspirit1b@howstuffworks.com\",\n" +
            "  \"password\": \"x7SMZf2\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"1b622599-6b08-4bef-b170-d9a97a290e54\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"6.149.64.117\",\n" +
            "  \"proxyPort\": 8423129,\n" +
            "  \"proxyUser\": \"stibalt1b\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"eqVpDO\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 3629,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"vbartles1c@fotki.com\",\n" +
            "  \"password\": \"FlPOK1MAxMsF\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"223e25c8-ad48-4ac9-8c0b-791b12d42a43\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"140.19.50.176\",\n" +
            "  \"proxyPort\": 19846400,\n" +
            "  \"proxyUser\": \"cpedrielli1c\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"egJmmKXExImG\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 6904,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"pjansie1d@ibm.com\",\n" +
            "  \"password\": \"q6KgVK5\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"b554431d-16e1-40bc-bc7a-d2110716388a\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"68.77.92.250\",\n" +
            "  \"proxyPort\": 9836524,\n" +
            "  \"proxyUser\": \"esicely1d\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"snlGLHFz\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 4526,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"minnwood1e@wunderground.com\",\n" +
            "  \"password\": \"bq6OwRd\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"f51105f6-3a77-4e77-bb04-f071a0ed6a3c\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"240.131.58.31\",\n" +
            "  \"proxyPort\": 24775144,\n" +
            "  \"proxyUser\": \"awoolen1e\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"GFS6WG\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 7808,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"dmattheeuw1f@arstechnica.com\",\n" +
            "  \"password\": \"ICYMJMQp\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"bcf83d08-feaf-411b-93df-96941de93319\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"108.120.82.16\",\n" +
            "  \"proxyPort\": 26541814,\n" +
            "  \"proxyUser\": \"aseelbach1f\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"WIdFFTK9\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 4818,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"tride1g@dyndns.org\",\n" +
            "  \"password\": \"biGgtA2\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"c7f2187b-fbfc-443a-bd0e-bf6be3153727\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"169.8.102.110\",\n" +
            "  \"proxyPort\": 22319436,\n" +
            "  \"proxyUser\": \"sbicknell1g\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"aW3IwB\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 7967,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"hbossingham1h@usa.gov\",\n" +
            "  \"password\": \"yFt6l7Hnf\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"cc5becea-374a-4640-a167-b611309f62b5\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"241.115.180.197\",\n" +
            "  \"proxyPort\": 26488628,\n" +
            "  \"proxyUser\": \"melstub1h\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"ZUOWbAD\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 1448,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"sratledge1i@comsenz.com\",\n" +
            "  \"password\": \"o9lZCMpH2CdF\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"7cbe1245-b497-406d-87cf-422ce7b51537\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"176.164.207.21\",\n" +
            "  \"proxyPort\": 30714502,\n" +
            "  \"proxyUser\": \"crassmann1i\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"Wd4gd3fpZ7\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 4684,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"atourner1j@salon.com\",\n" +
            "  \"password\": \"BxoddA\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"91fc54ea-08d7-4c6a-a76c-ebc0962f9389\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"30.162.22.40\",\n" +
            "  \"proxyPort\": 8833200,\n" +
            "  \"proxyUser\": \"urehme1j\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"twi8uQGcAXa1\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 1593,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"lspurrett1k@ask.com\",\n" +
            "  \"password\": \"ORwImFc\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"e09d39c0-ce15-48d6-abd7-1b9ff35eea3e\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"233.214.218.184\",\n" +
            "  \"proxyPort\": 19837007,\n" +
            "  \"proxyUser\": \"tcrock1k\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"Q4QuaXKlZX\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 2375,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"sstych1l@artisteer.com\",\n" +
            "  \"password\": \"U5eIxBHUw\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"779c0254-a1c2-4365-b38d-9adccf0831b3\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"104.40.244.230\",\n" +
            "  \"proxyPort\": 6116982,\n" +
            "  \"proxyUser\": \"cturfus1l\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"RVF4GxUyksoU\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 4352,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"ecawker1m@meetup.com\",\n" +
            "  \"password\": \"UhunJ8ihMh\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"f9922719-fc0d-4b48-87b5-5145df631d37\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"106.120.131.71\",\n" +
            "  \"proxyPort\": 26470696,\n" +
            "  \"proxyUser\": \"gcafferty1m\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"IrSsMX\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 4959,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"hlardier1n@1und1.de\",\n" +
            "  \"password\": \"sHpGyDywfiX8\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"923ed39d-0ab6-4122-a667-1d502a0dacd4\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"91.235.226.85\",\n" +
            "  \"proxyPort\": 3060924,\n" +
            "  \"proxyUser\": \"aspratling1n\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"o6VAWZlR1yl\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 8503,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"lbuddle1o@sogou.com\",\n" +
            "  \"password\": \"tK63gQk1\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"b51953af-d723-4836-974e-3edb9d461187\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"224.191.79.81\",\n" +
            "  \"proxyPort\": 16774321,\n" +
            "  \"proxyUser\": \"vbiesterfeld1o\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"u1EhdNYk\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 1928,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"cmcdonogh1p@apache.org\",\n" +
            "  \"password\": \"bi2aDvr\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"6e13ddeb-287e-4fcd-86bf-cabeee32b49a\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"51.48.206.69\",\n" +
            "  \"proxyPort\": 25417678,\n" +
            "  \"proxyUser\": \"wlumox1p\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"px89E4mJdSt\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 7324,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"irockey1q@e-recht24.de\",\n" +
            "  \"password\": \"keBFSWoZ2ih\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"f275b20d-8159-4753-82db-217f1f59a03d\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"181.216.6.71\",\n" +
            "  \"proxyPort\": 27135836,\n" +
            "  \"proxyUser\": \"kyarnall1q\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"Say1JLbtz\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 1871,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"oserle1r@clickbank.net\",\n" +
            "  \"password\": \"0OyVXAxCo9\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"e51fbdf3-363f-436a-a6de-88297885985e\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"155.143.144.31\",\n" +
            "  \"proxyPort\": 30035830,\n" +
            "  \"proxyUser\": \"mbranche1r\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"mhWIpeN\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 3359,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"fborleace1s@vkontakte.ru\",\n" +
            "  \"password\": \"UF3JmI\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"97dbfc10-d0fc-4cf1-a3f4-f4ef5a491bf7\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"219.137.189.119\",\n" +
            "  \"proxyPort\": 10464086,\n" +
            "  \"proxyUser\": \"jbigby1s\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"spDWS6\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 1149,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"gcottom1t@nih.gov\",\n" +
            "  \"password\": \"vuE6yKS5\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"c24a0d8c-07ba-4783-9708-b1bfb982ac75\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"21.126.235.85\",\n" +
            "  \"proxyPort\": 22067977,\n" +
            "  \"proxyUser\": \"mconlaund1t\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"SUGbOZ\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 5753,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"ccorfield1u@chronoengine.com\",\n" +
            "  \"password\": \"QYh0KCd\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"fdf577d8-5f25-4264-a6e4-8e0fd55381a7\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"31.81.149.209\",\n" +
            "  \"proxyPort\": 28613601,\n" +
            "  \"proxyUser\": \"nbevens1u\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"jlOprV0mdI\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 9832,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"mcrilley1v@twitpic.com\",\n" +
            "  \"password\": \"zoG6YLSYm\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"9802a91f-cf98-433b-925d-2435b6c96928\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"234.185.79.123\",\n" +
            "  \"proxyPort\": 14425502,\n" +
            "  \"proxyUser\": \"sbloyes1v\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"9AQISI2\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 6972,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"bcamelin1w@infoseek.co.jp\",\n" +
            "  \"password\": \"OA3eGGa5wB\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"b6c493e7-0ace-4995-8b87-919a8fe66854\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"191.34.130.230\",\n" +
            "  \"proxyPort\": 1757638,\n" +
            "  \"proxyUser\": \"mlabeuil1w\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"FHxYmtoMMc\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 6887,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"acopas1x@joomla.org\",\n" +
            "  \"password\": \"Yw0N5ChO\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"fe28b681-2e84-488d-bb80-eb8db3aa40d1\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"230.177.243.0\",\n" +
            "  \"proxyPort\": 24802357,\n" +
            "  \"proxyUser\": \"dglasper1x\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"GlvWnY76C0q7\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 4593,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"ralsina1y@cnbc.com\",\n" +
            "  \"password\": \"Znm49crOL17\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"359720d8-5f5e-4964-8d9a-1d21c32b1a0e\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"230.0.254.199\",\n" +
            "  \"proxyPort\": 28289558,\n" +
            "  \"proxyUser\": \"mrustadge1y\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"NoONNXNl0y7\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 4108,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"gdemoge1z@epa.gov\",\n" +
            "  \"password\": \"7hIQipQR\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"d7d51b44-29be-4dd0-8304-b469a2bdf083\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"21.252.203.215\",\n" +
            "  \"proxyPort\": 359413,\n" +
            "  \"proxyUser\": \"wdaw1z\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"omMhY93BQyj\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 9984,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"dlargan20@joomla.org\",\n" +
            "  \"password\": \"14XzEAN9k9ly\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"346b7e84-2c04-41c2-9129-c336dd4ccdc8\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"42.182.3.146\",\n" +
            "  \"proxyPort\": 391782,\n" +
            "  \"proxyUser\": \"sdann20\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"7tsEAy7IsL\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 5849,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"kgriffiths21@upenn.edu\",\n" +
            "  \"password\": \"IBi2sZeNg\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"b41f9f63-70a6-462f-ba4e-27f5520e3f8a\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"142.45.221.53\",\n" +
            "  \"proxyPort\": 4496433,\n" +
            "  \"proxyUser\": \"bterram21\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"5265k2n\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 4641,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"mloxdale22@yellowbook.com\",\n" +
            "  \"password\": \"st5SvuMZ\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"f961a450-9d50-4194-aa28-2cd8bd470e38\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"76.9.224.242\",\n" +
            "  \"proxyPort\": 13389674,\n" +
            "  \"proxyUser\": \"sambrosio22\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"q7OvHYTEw\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 6689,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"tlaflin23@merriam-webster.com\",\n" +
            "  \"password\": \"LQTqdA1e\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"b8915d73-81bd-4ea0-b81c-2e64f08e416f\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"96.6.240.132\",\n" +
            "  \"proxyPort\": 28342811,\n" +
            "  \"proxyUser\": \"tmcpike23\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"GjE2vI12rrb\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 3085,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"oseaborn24@bloomberg.com\",\n" +
            "  \"password\": \"vd6xB1\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"8c52f4c2-0482-496a-8533-fd3e64545f10\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"218.87.250.50\",\n" +
            "  \"proxyPort\": 11529214,\n" +
            "  \"proxyUser\": \"lcorbitt24\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"8E6rOp0DWRF\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 5059,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"lbeauvais25@amazon.co.jp\",\n" +
            "  \"password\": \"o80LwXDLwV\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"ca9785a8-cd6a-4032-b481-fb7dafe2d250\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"238.46.216.45\",\n" +
            "  \"proxyPort\": 589918,\n" +
            "  \"proxyUser\": \"jloggie25\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"pjkWorTZB\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 4123,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"acrosio26@usa.gov\",\n" +
            "  \"password\": \"luGZPR\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"877ab432-e323-4335-83b8-d66202b85840\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"78.99.73.89\",\n" +
            "  \"proxyPort\": 21810580,\n" +
            "  \"proxyUser\": \"rmursell26\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"F3zvbSL\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 7401,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"rkennington27@instagram.com\",\n" +
            "  \"password\": \"VwhUgs\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"d0a2a1e8-0885-4d07-8b5f-eaa9701b5dec\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"104.234.183.94\",\n" +
            "  \"proxyPort\": 8484695,\n" +
            "  \"proxyUser\": \"nwalcot27\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"HzXUMpD\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 8346,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"oshrubsall28@nytimes.com\",\n" +
            "  \"password\": \"DKKoP1LYFBk1\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"2ea73591-9bed-4af2-b67c-bd015b1492ca\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"181.188.159.246\",\n" +
            "  \"proxyPort\": 8989504,\n" +
            "  \"proxyUser\": \"klambrecht28\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"RnGBD7zstEL\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 4409,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"zsandbrook29@blogger.com\",\n" +
            "  \"password\": \"u4mUyTA7Qi\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"179476b0-61c3-4abe-9646-c9ac1b14979b\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"78.123.64.129\",\n" +
            "  \"proxyPort\": 6023728,\n" +
            "  \"proxyUser\": \"lshemmin29\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"85DPUeoxP2\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 5543,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"msavidge2a@hubpages.com\",\n" +
            "  \"password\": \"9DSQuE6naOoS\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"5072e5c4-0710-4c88-a020-3fb9865282f5\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"182.31.228.132\",\n" +
            "  \"proxyPort\": 2096319,\n" +
            "  \"proxyUser\": \"bmarquis2a\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"mUKQJIVrHx\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 4236,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"cdulen2b@geocities.jp\",\n" +
            "  \"password\": \"9a8DhC\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"d1b00e7e-1501-484d-b477-9c76765ebf05\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"8.100.156.193\",\n" +
            "  \"proxyPort\": 17155484,\n" +
            "  \"proxyUser\": \"ajobson2b\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"qi3coGVRdU6E\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 1402,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"cmaslen2c@artisteer.com\",\n" +
            "  \"password\": \"WXNrTorVga\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"1c2592bd-3c32-47a3-a1b1-02395fe157a4\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"221.62.238.39\",\n" +
            "  \"proxyPort\": 27986665,\n" +
            "  \"proxyUser\": \"mrainsden2c\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"SCk8FeQqX\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 9424,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"avaux2d@amazon.co.uk\",\n" +
            "  \"password\": \"WufnneuI\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"10374253-1390-4354-90ce-23a1ec7a0ce7\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"171.186.61.59\",\n" +
            "  \"proxyPort\": 4886034,\n" +
            "  \"proxyUser\": \"nvankeev2d\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"vUS0D5\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 5314,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"cgowanlock2e@wikimedia.org\",\n" +
            "  \"password\": \"feCU5so4\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"3f0a3afe-4b34-4100-8f3c-3cfb1babab20\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"87.15.44.224\",\n" +
            "  \"proxyPort\": 1145035,\n" +
            "  \"proxyUser\": \"smitchel2e\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"pcxRkuIP50\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 6632,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"cleitche2f@nationalgeographic.com\",\n" +
            "  \"password\": \"2JRMay\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"7a386daa-cca7-4fee-a125-a14e4a079184\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"224.146.148.199\",\n" +
            "  \"proxyPort\": 19809701,\n" +
            "  \"proxyUser\": \"fgrund2f\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"bJ84vfqiGUP\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 1880,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"fwreak2g@goodreads.com\",\n" +
            "  \"password\": \"e4HqbE93K\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"0ec31ac9-d3cc-4f82-9436-5d01f392cc2b\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"69.194.201.238\",\n" +
            "  \"proxyPort\": 2310133,\n" +
            "  \"proxyUser\": \"croles2g\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"whrQS89xUaH\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 9185,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"jutridge2h@buzzfeed.com\",\n" +
            "  \"password\": \"wxvQtBPf9\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"d1f45edb-7525-4a82-97e9-9db0ac229c2c\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"65.153.119.129\",\n" +
            "  \"proxyPort\": 27850534,\n" +
            "  \"proxyUser\": \"ewixey2h\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"YGSTmWMqnx\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 8384,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"mjurczik2i@a8.net\",\n" +
            "  \"password\": \"PS51f8rj\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"977618af-1d69-4b57-a720-17c3d961d21b\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"44.122.138.17\",\n" +
            "  \"proxyPort\": 21992549,\n" +
            "  \"proxyUser\": \"handreas2i\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"QGslNYpHjDt\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 9569,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"koreilly2j@cbslocal.com\",\n" +
            "  \"password\": \"cnasaMhQTn\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"dbed2ff1-3c35-40fb-867a-73e99ce7d99a\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"225.231.52.121\",\n" +
            "  \"proxyPort\": 6049803,\n" +
            "  \"proxyUser\": \"alade2j\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"Jp4fxMCu5\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 1689,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"laldham2k@dion.ne.jp\",\n" +
            "  \"password\": \"fqEzVkzF61\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"838bec6b-af01-48aa-9254-3d3cbfc61d18\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"155.19.164.130\",\n" +
            "  \"proxyPort\": 5889343,\n" +
            "  \"proxyUser\": \"cchurches2k\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"LG3r9w4\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 3169,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"cadger2l@dropbox.com\",\n" +
            "  \"password\": \"cpP4h8PBnhpQ\",\n" +
            "  \"status\": \"Offline\",\n" +
            "  \"taskId\": \"a4af9236-d058-4e6a-9e05-6627ce5cbe08\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"143.65.230.244\",\n" +
            "  \"proxyPort\": 4993289,\n" +
            "  \"proxyUser\": \"hsieur2l\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"2iraoF\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 1188,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"pvalek2m@elegantthemes.com\",\n" +
            "  \"password\": \"rqFxINSs2\",\n" +
            "  \"status\": \"Banned\",\n" +
            "  \"taskId\": \"45dc29f1-68c7-492b-871d-0f67f256c8f5\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"63.120.140.130\",\n" +
            "  \"proxyPort\": 3792474,\n" +
            "  \"proxyUser\": \"cgraben2m\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"MiPVRyD\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 2828,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"modempsey2n@yahoo.com\",\n" +
            "  \"password\": \"dYmD8u\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"f6e89e8b-76e0-4710-877b-407702f8a750\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"148.65.240.4\",\n" +
            "  \"proxyPort\": 1872932,\n" +
            "  \"proxyUser\": \"vmackinder2n\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"y8mCJ53naBI\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 4301,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"rpurviss2o@cornell.edu\",\n" +
            "  \"password\": \"It1qWJ8d\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"57a8144c-daac-43e8-b862-0f360b41d986\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"16.5.58.73\",\n" +
            "  \"proxyPort\": 28459815,\n" +
            "  \"proxyUser\": \"jfarnon2o\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"nyzZHSFkH9\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 8897,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"mrothon2p@vimeo.com\",\n" +
            "  \"password\": \"88nOKJ7I0i\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"b6b399f4-3029-4c44-b4e4-d4503a9358dd\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"223.244.178.143\",\n" +
            "  \"proxyPort\": 8737518,\n" +
            "  \"proxyUser\": \"ephillimore2p\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"ivhzkjYB\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 5155,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"ccardus2q@bravesites.com\",\n" +
            "  \"password\": \"BFbfDBt6B9H\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"4b1f6615-6ea9-49c1-9872-4e52ea70a44a\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"62.134.150.155\",\n" +
            "  \"proxyPort\": 29125072,\n" +
            "  \"proxyUser\": \"bhaverson2q\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"Fq6Ph9buzD61\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}, {\n" +
            "  \"pin\": 7697,\n" +
            "  \"id\": null,\n" +
            "  \"username\": \"spennetti2r@cbc.ca\",\n" +
            "  \"password\": \"W5vCpYzb\",\n" +
            "  \"status\": \"Online\",\n" +
            "  \"taskId\": \"df663e77-56c6-4cd0-9dcd-5ab5dba92970\",\n" +
            "  \"created\": null,\n" +
            "  \"proxyHost\": \"5.20.132.189\",\n" +
            "  \"proxyPort\": 15860476,\n" +
            "  \"proxyUser\": \"nseamans2r\",\n" +
            "  \"homeWorld\": null,\n" +
            "  \"proxyPass\": \"TzMVwGh8uIAM\",\n" +
            "  \"tags\": null,\n" +
            "  \"completedQuests\": null,\n" +
            "  \"lastRecordedStats\": null,\n" +
            "  \"lastActive\": null,\n" +
            "  \"config\": null\n" +
            "}]";
    private CollectionReference accountReference;

    @PostConstruct
    public void setup() {
        this.accountReference = firestore.collection(FirebaseCollection.ACCOUNTS);

//        this.writeMan();
    }

    public List<AccountDetails> getAvailableAccounts() {
        return this.getAllAccounts().stream().filter(account -> account.getTaskId() == null).collect(Collectors.toList());
    }

    public List<AccountDetails> getAllAccounts() {
        List<AccountDetails> accounts = new ArrayList<>();
        try {
            List<QueryDocumentSnapshot> documents;
            documents = this.accountReference.get().get().getDocuments();

            for (DocumentSnapshot document : documents) {
                AccountDetails accountDetails = document.toObject(AccountDetails.class);
                accounts.add(accountDetails);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return accounts;
    }
//    TODO: For writing mock accounts into the DB.
//    public void writeMan() {
//        Gson gson = new Gson();
//        List<Object> jsonElement = gson.fromJson(this.json, List.class);
//        for (Object d: jsonElement) {
//            AccountDetails accountDetails = gson.fromJson(d.toString(), AccountDetails.class);
//
//            accountDetails.completedQuests = Collections.emptyList();
//
//            Map<String, Integer> mockStats = new HashMap<>();
//            Arrays.stream(Skill.values()).map((val) -> val.toString().toLowerCase()).collect(Collectors.toList()).forEach(skill -> {
//                mockStats.put(skill, NumberUtil.getRandomNumber(50, 99));
//            });
//
//            accountDetails.lastRecordedStats = mockStats;
////            System.out.println("Writing: " + accountDetails);
//            accountDetails.setTaskId(null);
//            accountDetails.setHomeWorld(Integer.toString(NumberUtil.getRandomNumber(1, 30)));
//            System.out.println("though:: " + accountDetails.getUsername());
//            this.accountReference.document(accountDetails.getUsername()).set(accountDetails);
//        }
//    }
}
